import { BudgetLimit, CreditCard, InvestmentGoal, InvestmentContribution, Transaction } from '../types/finance';

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card-1',
    name: 'Nubank Ultravioleta',
    limit: 8000,
    closingDay: 24,
    dueDay: 3,
    color: '#820ad1',
    bank: 'Nubank',
  },
  {
    id: 'card-2',
    name: 'Inter Mastercard Black',
    limit: 5000,
    closingDay: 15,
    dueDay: 22,
    color: '#ff7a00',
    bank: 'Banco Inter',
  },
  {
    id: 'card-3',
    name: 'Itaú Click Visa',
    limit: 4500,
    closingDay: 20,
    dueDay: 28,
    color: '#004990',
    bank: 'Itaú Unibanco',
  },
  {
    id: 'card-4',
    name: 'Santander SX',
    limit: 3500,
    closingDay: 10,
    dueDay: 18,
    color: '#cc092f',
    bank: 'Santander',
  },
];

export const INITIAL_INVESTMENTS: InvestmentGoal[] = [
  {
    id: 'inv-1',
    name: 'Reserva de Emergência',
    category: 'emergency',
    institution: 'Nubank (Caixinha RDB 100% CDI)',
    currentAmount: 14500,
    targetAmount: 25000,
    monthlyContribution: 800,
    color: '#10b981',
    expectedReturnAnnual: 10.75,
    notes: 'Reserva para cobrir 6 meses de custos fixos com liquidez diária imediata.',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'inv-2',
    name: 'Tesouro Selic / Renda Fixa',
    category: 'cdb_fixed',
    institution: 'Tesouro Direto / XP',
    currentAmount: 8200,
    targetAmount: 15000,
    monthlyContribution: 500,
    color: '#3b82f6',
    expectedReturnAnnual: 10.9,
    notes: 'Investimento seguro e de alta rentabilidade garantido pelo governo federal.',
    createdAt: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'inv-3',
    name: 'Fundo Viagem de Férias',
    category: 'goals',
    institution: 'Banco Inter (LCI 95% CDI)',
    currentAmount: 3800,
    targetAmount: 6000,
    monthlyContribution: 400,
    color: '#f59e0b',
    expectedReturnAnnual: 9.8,
    notes: 'Meta para viagem de fim de ano com amigos/família.',
    createdAt: '2026-03-20T10:00:00.000Z',
  },
  {
    id: 'inv-4',
    name: 'Carteira de Ações & FIIs',
    category: 'stocks',
    institution: 'BTG Pactual',
    currentAmount: 5600,
    targetAmount: 20000,
    monthlyContribution: 300,
    color: '#8b5cf6',
    expectedReturnAnnual: 12.5,
    notes: 'Aportes focados em dividendos mensais de Fundos Imobiliários e boas empresas.',
    createdAt: '2026-04-05T10:00:00.000Z',
  },
];

export const INITIAL_CONTRIBUTIONS: InvestmentContribution[] = [
  {
    id: 'contrib-1',
    goalId: 'inv-1',
    type: 'deposit',
    amount: 800,
    date: '2026-09-05',
    notes: 'Aporte regular do salário de setembro',
    createdAt: '2026-09-05T12:00:00.000Z',
  },
  {
    id: 'contrib-2',
    goalId: 'inv-2',
    type: 'deposit',
    amount: 500,
    date: '2026-09-10',
    notes: 'Aporte mensal Tesouro Direto',
    createdAt: '2026-09-10T12:00:00.000Z',
  },
  {
    id: 'contrib-3',
    goalId: 'inv-3',
    type: 'deposit',
    amount: 400,
    date: '2026-09-12',
    notes: 'Caixinha de viagem',
    createdAt: '2026-09-12T12:00:00.000Z',
  },
];

export const INITIAL_BUDGET_LIMITS: BudgetLimit[] = [
  {
    id: 'limit-overall',
    category: 'overall',
    title: 'Limite Total Mensal de Gastos',
    monthlyLimit: 5500,
    alertThresholdPercent: 80,
    enabled: true,
  },
  {
    id: 'limit-credit-card',
    category: 'credit_card',
    title: 'Limite para Compras de Cartão',
    monthlyLimit: 2000,
    alertThresholdPercent: 80,
    enabled: true,
  },
  {
    id: 'limit-fixed-debt',
    category: 'fixed_debt',
    title: 'Teto para Dívidas Fixas',
    monthlyLimit: 3200,
    alertThresholdPercent: 90,
    enabled: true,
  },
  {
    id: 'limit-general',
    category: 'general_expenses',
    title: 'Limite para Gastos Variáveis',
    monthlyLimit: 800,
    alertThresholdPercent: 75,
    enabled: true,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // SETEMBRO 2026 (Mês Atual)
  // ENTRADAS: Salários & Comissões
  {
    id: 'tx-sep-01',
    type: 'income',
    category: 'salary',
    subCategory: 'Salário Mensal',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-09-05',
    paymentMethod: 'bank_transfer',
    isPaid: true,
    createdAt: '2026-09-05T08:00:00Z',
  },
  {
    id: 'tx-sep-02',
    type: 'income',
    category: 'commission',
    subCategory: 'Comissão de Vendas',
    description: 'Comissão Fechamento Contratos Q3',
    amount: 1950.0,
    date: '2026-09-15',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'tx-sep-03',
    type: 'income',
    category: 'freelance',
    subCategory: 'Consultoria',
    description: 'Consultoria UX / Web Design',
    amount: 650.0,
    date: '2026-09-22',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'tx-sep-04',
    type: 'income',
    category: 'commission',
    subCategory: 'Bônus Performance',
    description: 'Bônus por Atingimento de Meta Semanal',
    amount: 450.0,
    date: '2026-09-28',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-28T16:00:00Z',
  },

  // SAÍDAS: Dívidas Fixas (Setembro 2026)
  {
    id: 'tx-sep-05',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Habitação',
    description: 'Aluguel Apartamento',
    amount: 1750.0,
    date: '2026-09-05',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'tx-sep-06',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Condomínio',
    description: 'Taxa Condominial + Fundo Reserva',
    amount: 380.0,
    date: '2026-09-10',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'tx-sep-07',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Energia',
    description: 'Conta de Luz Enel',
    amount: 218.4,
    date: '2026-09-12',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-12T11:00:00Z',
  },
  {
    id: 'tx-sep-08',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Internet',
    description: 'Internet Fibra Óptica 600 Mega',
    amount: 129.9,
    date: '2026-09-15',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'tx-sep-09',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Saúde',
    description: 'Plano de Saúde Unimed',
    amount: 490.0,
    date: '2026-09-20',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-09-20T10:00:00Z',
  },

  // SAÍDAS: Compras de Cartão (Setembro 2026)
  {
    id: 'tx-sep-10',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Mercado',
    description: 'Supermercado Pão de Açúcar - Compras Mês',
    amount: 780.0,
    date: '2026-09-08',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    isPaid: true,
    createdAt: '2026-09-08T18:30:00Z',
  },
  {
    id: 'tx-sep-11',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 4/10)',
    amount: 329.9,
    date: '2026-09-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 4,
    totalInstallments: 10,
    isPaid: true,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'tx-sep-12',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Farmácia',
    description: 'Farmácia Drogasil - Medicamentos & Vitaminas',
    amount: 142.5,
    date: '2026-09-14',
    paymentMethod: 'credit_card',
    cardName: 'Inter Platinum',
    isPaid: true,
    createdAt: '2026-09-14T19:00:00Z',
  },
  {
    id: 'tx-sep-13',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Combustível',
    description: 'Abastecimento Posto Shell (Gasolina Aditivada)',
    amount: 245.0,
    date: '2026-09-18',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    isPaid: true,
    createdAt: '2026-09-18T08:15:00Z',
  },
  {
    id: 'tx-sep-14',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Alimentação',
    description: 'Jantar Restaurante Cantina Italiana',
    amount: 220.0,
    date: '2026-09-23',
    paymentMethod: 'credit_card',
    cardName: 'Inter Platinum',
    isPaid: true,
    createdAt: '2026-09-23T21:40:00Z',
  },
  {
    id: 'tx-sep-15',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Vestuário',
    description: 'Roupas e Calçados Zarpo (Parcela 2/3)',
    amount: 165.0,
    date: '2026-09-26',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 2,
    totalInstallments: 3,
    isPaid: false, // Pendente na fatura fechando
    createdAt: '2026-09-26T15:20:00Z',
  },

  // SAÍDAS: Gastos Variáveis (Setembro 2026)
  {
    id: 'tx-sep-16',
    type: 'expense',
    category: 'general_expenses',
    subCategory: 'Padaria & Lanches',
    description: 'Padaria Manhã & Café Especial',
    amount: 85.0,
    date: '2026-09-09',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'tx-sep-17',
    type: 'expense',
    category: 'general_expenses',
    subCategory: 'Transporte',
    description: 'Uber Corridas Semanais',
    amount: 94.6,
    date: '2026-09-17',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-17T17:30:00Z',
  },
  {
    id: 'tx-sep-18',
    type: 'expense',
    category: 'general_expenses',
    subCategory: 'Lazer',
    description: 'Cinema IMAX + Pipoca',
    amount: 110.0,
    date: '2026-09-21',
    paymentMethod: 'debit_card',
    isPaid: true,
    createdAt: '2026-09-21T20:00:00Z',
  },
  {
    id: 'tx-sep-19',
    type: 'expense',
    category: 'general_expenses',
    subCategory: 'Manutenção',
    description: 'Troca de Óleo e Filtro do Carro',
    amount: 230.0,
    date: '2026-09-27',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-09-27T10:00:00Z',
  },

  // PROJEÇÃO: OUTUBRO 2026 (Parcelas seguintes e despesas fixas)
  {
    id: 'tx-oct-01',
    type: 'income',
    category: 'salary',
    subCategory: 'Salário Mensal',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-10-05',
    paymentMethod: 'bank_transfer',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-oct-02',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Habitação',
    description: 'Aluguel Apartamento',
    amount: 1750.0,
    date: '2026-10-05',
    paymentMethod: 'boleto',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-oct-03',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 5/10)',
    amount: 329.9,
    date: '2026-10-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 5,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'tx-oct-04',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Condomínio',
    description: 'Taxa Condominial + Fundo Reserva',
    amount: 380.0,
    date: '2026-10-10',
    paymentMethod: 'boleto',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-oct-05',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Internet',
    description: 'Internet Fibra Óptica 600 Mega',
    amount: 129.9,
    date: '2026-10-15',
    paymentMethod: 'boleto',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-oct-06',
    type: 'expense',
    category: 'fixed_debt',
    subCategory: 'Saúde',
    description: 'Plano de Saúde Unimed',
    amount: 490.0,
    date: '2026-10-20',
    paymentMethod: 'boleto',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-oct-07',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Vestuário',
    description: 'Roupas e Calçados Zarpo (Parcela 3/3)',
    amount: 165.0,
    date: '2026-10-26',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 3,
    totalInstallments: 3,
    installmentGroupId: 'inst-roupas-zarpo',
    isPaid: false,
    createdAt: '2026-09-26T15:20:00Z',
  },

  // PROJEÇÃO: NOVEMBRO 2026
  {
    id: 'tx-nov-01',
    type: 'income',
    category: 'salary',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-11-05',
    paymentMethod: 'bank_transfer',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-nov-02',
    type: 'expense',
    category: 'fixed_debt',
    description: 'Aluguel Apartamento',
    amount: 1750.0,
    date: '2026-11-05',
    paymentMethod: 'boleto',
    isPaid: false,
    createdAt: '2026-09-28T12:00:00Z',
  },
  {
    id: 'tx-nov-03',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 6/10)',
    amount: 329.9,
    date: '2026-11-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 6,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },

  // PARCELAS SEGUINTES DO NOTEBOOK
  {
    id: 'tx-dec-01',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 7/10)',
    amount: 329.9,
    date: '2026-12-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 7,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'tx-jan-01',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 8/10)',
    amount: 329.9,
    date: '2027-01-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 8,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'tx-feb-01',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 9/10)',
    amount: 329.9,
    date: '2027-02-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 9,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'tx-mar-01',
    type: 'expense',
    category: 'credit_card',
    subCategory: 'Eletrônicos',
    description: 'Notebook Dell Inspiron (Parcela 10/10)',
    amount: 329.9,
    date: '2027-03-10',
    paymentMethod: 'credit_card',
    cardName: 'Nubank Ultravioleta',
    currentInstallment: 10,
    totalInstallments: 10,
    installmentGroupId: 'inst-notebook-dell',
    isPaid: false,
    createdAt: '2026-09-10T12:00:00Z',
  },

  // HISTÓRICO: AGOSTO 2026
  {
    id: 'tx-aug-01',
    type: 'income',
    category: 'salary',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-08-05',
    paymentMethod: 'bank_transfer',
    isPaid: true,
    createdAt: '2026-08-05T08:00:00Z',
  },
  {
    id: 'tx-aug-02',
    type: 'income',
    category: 'commission',
    description: 'Comissão Vendas Agosto',
    amount: 1700.0,
    date: '2026-08-15',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'tx-aug-03',
    type: 'expense',
    category: 'fixed_debt',
    description: 'Aluguel + Condomínio',
    amount: 2130.0,
    date: '2026-08-05',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'tx-aug-04',
    type: 'expense',
    category: 'fixed_debt',
    description: 'Contas (Luz, Internet, Saúde)',
    amount: 830.0,
    date: '2026-08-15',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'tx-aug-05',
    type: 'expense',
    category: 'credit_card',
    description: 'Fatura Cartão Nubank (Mercado, Compras)',
    amount: 1680.0,
    date: '2026-08-20',
    paymentMethod: 'credit_card',
    isPaid: true,
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'tx-aug-06',
    type: 'expense',
    category: 'general_expenses',
    description: 'Gastos Variáveis & Lazer',
    amount: 650.0,
    date: '2026-08-25',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-08-25T14:00:00Z',
  },

  // HISTÓRICO: JULHO 2026
  {
    id: 'tx-jul-01',
    type: 'income',
    category: 'salary',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-07-05',
    paymentMethod: 'bank_transfer',
    isPaid: true,
    createdAt: '2026-07-05T08:00:00Z',
  },
  {
    id: 'tx-jul-02',
    type: 'income',
    category: 'commission',
    description: 'Comissões de Vendas Julho',
    amount: 2200.0,
    date: '2026-07-15',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-07-15T11:00:00Z',
  },
  {
    id: 'tx-jul-03',
    type: 'expense',
    category: 'fixed_debt',
    description: 'Aluguel + Contas Fixas',
    amount: 2950.0,
    date: '2026-07-10',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-07-10T09:00:00Z',
  },
  {
    id: 'tx-jul-04',
    type: 'expense',
    category: 'credit_card',
    description: 'Fatura Nubank + Inter',
    amount: 1890.0,
    date: '2026-07-22',
    paymentMethod: 'credit_card',
    isPaid: true,
    createdAt: '2026-07-22T10:00:00Z',
  },
  {
    id: 'tx-jul-05',
    type: 'expense',
    category: 'general_expenses',
    description: 'Férias & Gastos Variáveis',
    amount: 920.0,
    date: '2026-07-26',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-07-26T16:00:00Z',
  },

  // HISTÓRICO: JUNHO 2026
  {
    id: 'tx-jun-01',
    type: 'income',
    category: 'salary',
    description: 'Salário Empresa TechCorp',
    amount: 6500.0,
    date: '2026-06-05',
    paymentMethod: 'bank_transfer',
    isPaid: true,
    createdAt: '2026-06-05T08:00:00Z',
  },
  {
    id: 'tx-jun-02',
    type: 'income',
    category: 'commission',
    description: 'Comissão Especial Metas Junho',
    amount: 1600.0,
    date: '2026-06-15',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-06-15T11:00:00Z',
  },
  {
    id: 'tx-jun-03',
    type: 'expense',
    category: 'fixed_debt',
    description: 'Aluguel + Contas Fixas',
    amount: 2920.0,
    date: '2026-06-10',
    paymentMethod: 'boleto',
    isPaid: true,
    createdAt: '2026-06-10T09:00:00Z',
  },
  {
    id: 'tx-jun-04',
    type: 'expense',
    category: 'credit_card',
    description: 'Fatura de Cartões',
    amount: 1740.0,
    date: '2026-06-22',
    paymentMethod: 'credit_card',
    isPaid: true,
    createdAt: '2026-06-22T10:00:00Z',
  },
  {
    id: 'tx-jun-05',
    type: 'expense',
    category: 'general_expenses',
    description: 'Gastos Variáveis Junho',
    amount: 580.0,
    date: '2026-06-25',
    paymentMethod: 'pix',
    isPaid: true,
    createdAt: '2026-06-25T14:00:00Z',
  },
];
